- src/main/java/com/twilio/sdk/resource/instance/Call.java
Just like dateCreated and dateUpdated
> Call startTime and endTime should be returned as Date objects 

- src/main/java/com/twilio/sdk/verbs/Conference.java
- src/test/java/com/twilio/sdk/verbs/ConferenceTest.java
> Resolve issue #181 by adding support for legacy ```setBeep``` behavior for the ```Conference``` verb

- src/main/java/com/twilio/sdk/TwilioRestClient.java
- src/main/java/com/twilio/sdk/TwilioTaskRouterClient.java
> Add TaskRouter endpoint override

- src/main/java/com/twilio/sdk/resource/instance/Message.java
- src/test/java/com/twilio/sdk/resource/instance/MessageTest.java
> Message.error_code is int, not string

- src/main/java/com/twilio/sdk/resource/instance/Call.java
- src/main/java/com/twilio/sdk/resource/instance/IncomingPhoneNumber.java
- src/test/java/com/twilio/sdk/resource/instance/CallTest.java
> Fix some minor property type issues

- pom.xml
- src/main/java/com/twilio/sdk/resource/Resource.java
> Remove Joda Time

- src/main/java/com/twilio/sdk/resource/instance/Recording.java
- src/test/java/com/twilio/sdk/resource/instance/RecordingTest.java
> Exposing price_unit property for Recording

- src/main/java/com/twilio/sdk/resource/instance/Account.java
- src/test/java/com/twilio/sdk/resource/instance/AccountTest.java
> Added sub resources for usage records

- src/main/java/com/twilio/sdk/resource/instance/pricing/MessagingCountry.java
- src/main/java/com/twilio/sdk/resource/instance/pricing/VoiceCountry.java
- src/test/java/com/twilio/sdk/resource/instance/pricing/MessagingCountryTest.java
- src/test/java/com/twilio/sdk/resource/instance/pricing/VoiceCountryTest.java
- src/test/resources/com/twilio/sdk/resource/instance/pricing/messaging_country.json
- src/test/resources/com/twilio/sdk/resource/instance/pricing/voice_country.json
https://github.com/twilio/twilio-java/issues/247
> Fix enum serialization in Voice/Messaging Pricing

- src/main/java/com/twilio/sdk/http/NetworkHttpClient.java
- src/main/java/com/twilio/sdk/http/NingHttpClient.java
- src/main/java/com/twilio/twiml/TwiML.java
https://github.com/twilio/twilio-java/issues/254
> Fix deletion in framework

- src/main/java/com/twilio/twiml/Say.java
As the spec https://jp.twilio.com/docs/api/twiml/say, more languages are needed to be supported.
Alice can speak more language.
> Add more languages for Say

- src/main/java/com/twilio/jwt/taskrouter/FilterRequirement.java
- src/main/java/com/twilio/jwt/taskrouter/Policy.java
- src/main/java/com/twilio/jwt/taskrouter/TaskRouterCapability.java
- src/test/java/com/twilio/jwt/taskrouter/PolicyTest.java
- src/test/java/com/twilio/jwt/taskrouter/TaskRouterCapabilityTest.java
- Utilize `channel` rather than `channel_id`
- Utilize JsonFormat on Enum to correctly generate JSON for `post_filter` and `query_filter`
- Add a new test for `post_filter`
> Fix twilio-java helper lib policies

- src/main/java/com/twilio/jwt/accesstoken/TaskRouterGrant.java
- src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java
> Adding TaskRouter grant

- src/main/java/com/twilio/example/ValidationExample.java
> Update Public Key Client Validation naming

- src/main/java/com/twilio/http/TwilioRestClient.java
@jingming @dlazerka @amormysh This should *actually* fix your problem.
> Fix exception on GAE using TwilioRestClient

- src/main/java/com/twilio/base/Reader.java
- src/main/java/com/twilio/exception/InvalidRequestException.java
- Also add new InvalidRequestException constructors.
> Add getPage and previousPage to base Reader

- src/main/java/com/twilio/twiml/Language.java
- src/test/java/com/twilio/twiml/SayTest.java
> [Issue-367] Update Language constants.

- src/main/java/com/twilio/twiml/Gather.java
- src/test/java/com/twilio/twiml/GatherTest.java
Used `String` as you can use `auto` as a value in addition to integers.
> Add speechTimeout support to Gather

- README.md
Point folks to the API reference part of the docs from this README
> Update Twilio API docs link in README

- src/main/java/com/twilio/jwt/accesstoken/VoiceGrant.java
- src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java
https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX
> Add incoming.allow to AccessToken VoiceGrant

- src/main/java/com/twilio/http/NetworkHttpClient.java
- src/main/java/com/twilio/http/ValidationClient.java
> Nest IOException inside APIException

- src/main/java/com/twilio/jwt/accesstoken/VoiceGrant.java
- src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java
https://issues.corp.twilio.com/browse/CLIENT-4598
> CLIENT-4598 | Fix null incomingAllow bug and add test

- pom.xml
- src/test/java/com/twilio/http/NetworkHttpClientTest.java
> Bump JMockit version for minimum compatibility with Java 11

- src/main/java/com/twilio/type/Client.java
- src/test/java/com/twilio/type/ClientTest.java
Similar to https://github.com/twilio/twilio-csharp/pull/456
> Prefix client identifiers with 'client:' if not already prefixed

- src/main/java/com/twilio/rest/api/v2010/account/Call.java
- src/main/java/com/twilio/rest/api/v2010/account/CallCreator.java
Relates to https://github.com/twilio/twilio-csharp/issues/402
> Update the call create 'from' param to be endpoint type for client identifier support

- pom.xml
> jackson 2.9.9

- src/main/java/com/twilio/type/SubscribeRule.java
- src/main/java/com/twilio/type/SubscribeRulesUpdate.java
- src/test/java/com/twilio/type/SubscribeRuleTest.java
- src/test/java/com/twilio/type/TypeTest.java
> Add SubscribeRule and SubscribeRulesUpdate

- .gitignore
> Ignore local settings

- .gitignore
One more setting file popped in that should not be committed. 
> Remove VS Code settings

- src/main/java/com/twilio/type/IceServer.java
- src/test/java/com/twilio/rest/api/v2010/account/TokenTest.java
- src/test/java/com/twilio/type/IceServerTest.java
> Add urls property in ice servers

- .travis.yml
- owasp-dependency-checker-suppressions.xml
- pom.xml
> Security vulnerability fix by updating jackson-databind version to 2.9.9.1

- AUTHORS.md
> add [Sean Sullivan] to authors document

- pom.xml
> Upgrade maven-javadoc-plugin to 3.1.1

- pom.xml
> Upgrade maven-source-plugin to 3.1.0

- pom.xml
> fix Javadoc copyright year

- src/main/java/com/twilio/security/RequestValidator.java
- src/test/java/com/twilio/security/RequestValidatorTest.java
> added request validation for urls with and without ports

- pom.xml
> chore: upgrade jackson to version 2.10.1

- README.md
Relates to https://github.com/twilio/twilio-java/issues/493
> docs: add an example for handling exceptions

- pom.xml
reference: https://github.com/TNG/ArchUnit/releases
> chore: upgrade archunit to version 0.12.0

- pom.xml
> chore: upgrade jackson to 2.10.2

- pom.xml
Updated jjwt dependency to the latest version as requested in issue #505 .
Closes #505 .
> chore: update jjwt to v0.9.1

- pom.xml
> chore: Upgrade archunit to version 0.13.0

- pom.xml
- src/test/java/com/twilio/compliance/ComplianceTest.java
> test: use [equalsverifier] library to verify 'equals' methods

- pom.xml
> chore: upgrade jackson to 2.10.3

- README.md
> docs: instructions on building your own local .jar

- pom.xml
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.4
> chore: bump jackson 2.10.4

- README.md
> docs: link to descriptive exception types

- src/main/java/com/twilio/base/Page.java
- src/main/java/com/twilio/base/Reader.java
- src/main/java/com/twilio/converter/PrefixedCollapsibleMap.java
- src/main/java/com/twilio/http/NetworkHttpClient.java
- src/main/java/com/twilio/http/ValidationClient.java
- src/main/java/com/twilio/http/ValidationInterceptor.java
- src/main/java/com/twilio/jwt/accesstoken/VoiceGrant.java
- src/main/java/com/twilio/jwt/client/ClientCapability.java
- src/main/java/com/twilio/jwt/taskrouter/Policy.java
- src/main/java/com/twilio/jwt/taskrouter/PolicyUtils.java
- src/main/java/com/twilio/jwt/taskrouter/TaskRouterCapability.java
- src/main/java/com/twilio/jwt/validation/RequestCanonicalizer.java
- src/main/java/com/twilio/jwt/validation/ValidationToken.java
- src/main/java/com/twilio/twiml/TwiML.java
- src/main/java/com/twilio/type/Sip.java
- src/test/java/com/twilio/compliance/ComplianceTest.java
- src/test/java/com/twilio/converter/PromoterTest.java
- src/test/java/com/twilio/jwt/client/ClientCapabilityTest.java
- src/test/java/com/twilio/jwt/taskrouter/PolicyUtilsTest.java
- src/test/java/com/twilio/jwt/taskrouter/TaskRouterCapabilityTest.java
- src/test/java/com/twilio/jwt/validation/RequestCanonicalizerTest.java
- src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
- src/test/java/com/twilio/taskrouter/WorkflowTest.java
- src/test/java/com/twilio/type/OutboundPrefixPriceTest.java
- src/test/java/com/twilio/type/OutboundSmsPriceTest.java
- src/test/java/com/twilio/type/SubscribeRuleTest.java
Relates to https://github.com/twilio/twilio-java/issues/511
> chore: drop some of the Guava usage which is easily replaced

- pom.xml
Closes #562 #563 #564 #548 #552
> chore: upgrade jackson and HTTP dependencies

- src/main/java/com/twilio/taskrouter/TaskRouting.java
- src/main/java/com/twilio/taskrouter/Workflow.java
- src/main/java/com/twilio/taskrouter/WorkflowRule.java
- src/main/java/com/twilio/taskrouter/WorkflowRuleTarget.java
- src/main/java/com/twilio/twiml/TwiML.java
- src/main/java/com/twilio/type/FeedbackIssue.java
- src/main/java/com/twilio/type/IceServer.java
- src/main/java/com/twilio/type/InboundCallPrice.java
- src/main/java/com/twilio/type/InboundSmsPrice.java
- src/main/java/com/twilio/type/OutboundCallPrice.java
- src/main/java/com/twilio/type/OutboundCallPriceWithOrigin.java
- src/main/java/com/twilio/type/OutboundPrefixPrice.java
- src/main/java/com/twilio/type/OutboundPrefixPriceWithOrigin.java
- src/main/java/com/twilio/type/OutboundSmsPrice.java
- src/main/java/com/twilio/type/PhoneNumberCapabilities.java
- src/main/java/com/twilio/type/PhoneNumberPrice.java
- src/main/java/com/twilio/type/SubscribeRule.java
- src/main/java/com/twilio/type/SubscribeRulesUpdate.java
Replacing with Lombok's @ToString.
> chore: finish dropping Guava 'MoreObjects' usage

- src/test/java/com/twilio/http/LoggingTest.java
> fix: no longer using log4j test config

- pom.xml
> chore: update jackson dependency

- pom.xml
bump dependencies:  junit, archunit, equalsverifier
> chore: bump dependencies

- src/main/java/com/twilio/http/TwilioRestClient.java
Invoke request.constructURL() to get the full url
(which includes the region)
> fix: log correct URL in TwilioRestClient

- pom.xml
upgrade to equalsverifier 3.6.1
> chore: equalsverifier 3.6.1

- src/main/java/com/twilio/taskrouter/WorkflowRuleTarget.java
- src/test/java/com/twilio/taskrouter/WorkflowRuleTargetTest.java
Adds known_worker_sid and known_worker_friendly_name fields to WorkflowRuleTarget in order to support known agent routing feature offered by TaskRouter.
> feat:Update WorkflowRuleTarget to support Known Agent Routing

- pom.xml
upgrade to latest version of ArchUnit
> chore: archunit 0.19.0

- src/main/java/com/twilio/http/Request.java
- src/test/java/com/twilio/http/RequestTest.java
Jira Ticket: https://issues.corp.twilio.com/browse/DI-1196
> fix: System Information Leak

- pom.xml
> chore: maven-enforcer-plugin 3.0.0

- pom.xml
latest version: lombok 1.18.16
> chore: lombok 1.18.16

- .github/workflows/test-and-deploy.yml
- pom.xml
- src/test/java/com/twilio/ClusterTest.java
- src/test/java/com/twilio/TwilioTest.java
- src/test/java/com/twilio/base/ReaderTest.java
- src/test/java/com/twilio/http/NetworkHttpClientTest.java
- src/test/java/com/twilio/http/TwilioRestClientTest.java
- src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
Added cluster test changes
Test run : https://github.com/kridai/twilio-java/runs/6567459754?check_suite_focus=true
CLoses : DII-281
> chore: add cluster test

- pom.xml
- src/main/java/com/twilio/Twilio.java
- src/test/java/com/twilio/TwilioTest.java
- src/test/java/com/twilio/http/NetworkHttpClientTest.java
- src/test/java/com/twilio/http/ResponseTest.java
- src/test/java/com/twilio/http/TwilioRestClientTest.java
- src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java
- src/test/java/com/twilio/jwt/client/ClientCapabilityTest.java
- src/test/java/com/twilio/jwt/taskrouter/TaskRouterCapabilityTest.java
- src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
> chore(DII-412): jmockit to mockito migration

- .github/workflows/test-and-deploy.yml
- pom.xml
Closes: DII-426
Added java 8 support back
> fix(DII-426): added back Java 8 support 

- src/test/java/com/twilio/compliance/ComplianceTest.java
This PR: 
Currently, the class `ArchivedCall` follows a different format for constructors and overridden methods (like `equals()`) so the basic sanity/ acceptance fails for this class. This PR creates an exception for variant classes like such, while performing compliance testing. 
> fix: improve compliance tests

- src/test/java/com/twilio/compliance/ComplianceTest.java
> fix: fixing compliance test

- src/main/java/com/twilio/http/Response.java
- src/test/java/com/twilio/http/ResponseTest.java
Fixes DII-573
Adding a fix for the issue found [here](https://github.com/twilio/twilio-java/issues/633).  
> fix: fix repeated get content calls issue

- pom.xml
- src/main/java/com/twilio/example/ValidationExample.java
- src/main/java/com/twilio/http/Request.java
- src/main/java/com/twilio/security/RequestValidator.java
closes #713
Removes the dependency on javax.xml.bind. (JAXB)
> misc: remove dependency on javax jaxb-api

- src/main/java/com/twilio/jwt/taskrouter/Policy.java
- src/test/java/com/twilio/jwt/taskrouter/PolicyTest.java
The test in com.twilio.jwt.taskrouter.PolicyTest#testToJsonexpress non-deterministic behaviour and thus fail with nondex. The fix is adding the annotation JSONPropertyOrder and changing the order of the json attributes to ensure determinism.
> fix: Fixing Flaky Tests

- src/main/java/com/twilio/http/Request.java
- Handle String.valueOf null string condition
> fix: add null string check

- src/main/java/com/twilio/http/Request.java
> fix: add request null check

- pom.xml
> fix: moving org.json to test scope

- src/main/java/com/twilio/http/Request.java
- src/main/java/com/twilio/http/ValidationClient.java
- src/test/java/com/twilio/http/RequestTest.java
- src/test/java/com/twilio/http/ValidationClientTest.java
Fixes [DII-1005](https://issues.corp.twilio.com/browse/DII-1005)
This PR: 
Supports sending json payload in Http Requests. 
> feat: support json content in requests

- Makefile
> fix: Update Makefile to test changelog genx

- src/main/java/com/twilio/constant/EnumConstants.java
add enum to main branch as well.
> chore: added content type enum

- src/main/java/com/twilio/constant/EnumConstants.java
- src/main/java/com/twilio/http/Request.java
Add content type enum to request
> chore: Add content type enum to request

- src/main/java/com/twilio/example/ValidationExample.java
removing setting region from validation example
> chore: update validation example

- src/main/java/com/twilio/Twilio.java
- src/test/java/com/twilio/TwilioTest.java
Update ValidateSslCertificate method in accordance with recent changes to the security testing method
> fix: Update ValidateSslCertificate method changes to the security testing method

- src/main/java/com/twilio/exception/ApiException.java
Added constructor in api exception so that http status can be set even when restException is null.
> chore: added constructor in api exception

- src/main/java/com/twilio/exception/ApiException.java
> chore: add-constructor-apiexception

- pom.xml
- src/main/java/com/twilio/Twilio.java
> chore: changed java version

- pom.xml
Since the deprecation of Java 11, we are seeing this [error](https://github.com/twilio/twilio-java/actions/runs/8507009654/job/23298209647#step:9:6272) in deploy stage. This is a known bug in nexus staging maven plugin which has been fixed in v1.6.13. Refer this [discussion](https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco). Bumping the plugin version in pom.xml
> chore: bumping nexus staging maven plugin version

- src/main/java/com/twilio/rest/numbers/v1/PortingPortInPhoneNumber.java
- src/test/java/com/twilio/compliance/ComplianceTest.java
com.twilio.rest.numbers.v1.PortingPortInPhoneNumber does not have response due to which it is not creating constructor and equals and hashcode methods thus failing compliance test.
Ignoring this file in compliance test.
> chore: add variant class to compliance tests

- pom.xml
Adding this [workaround](https://github.com/apache/pulsar/issues/13126) for failing tests
> chore: Update pom.xml

- src/main/java/com/twilio/rest/numbers/v1/PortingWebhookConfigurationDelete.java
- src/test/java/com/twilio/compliance/ComplianceTest.java
oai-generator PR: https://github.com/twilio/twilio-oai-generator/pull/575
> chore: adding variant class

- examples/Content.md
- examples/PreviewMessaging.md
> docs: added json examples

- src/main/java/com/twilio/http/bearertoken/OrgsTokenManager.java
- src/main/java/com/twilio/rest/previewiam/organizations/UserReader.java
- src/main/java/com/twilio/rest/previewiam/v1/Authorize.java
- src/main/java/com/twilio/rest/previewiam/v1/AuthorizeFetcher.java
- src/main/java/com/twilio/rest/previewiam/v1/Token.java
- src/main/java/com/twilio/rest/previewiam/v1/TokenCreator.java
Making [iam_organization](https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_iam_organizations.yaml) spec file as versionless and generating the code again.
Updated token manager with the correct Token path.
> fix: making previewiam versionless

- README.md
Updated beta feature in twilio-java.
> chore: updated readme for Beta flag

- README.md
updated readme with Orgs Example
> chore: updated readme with Orgs example

- src/test/java/com/twilio/compliance/ComplianceTest.java
> chore: disable java test

- src/test/java/com/twilio/compliance/ComplianceTest.java
> chore: enable java test

- pom.xml
- src/main/java/com/twilio/Twilio.java
- src/test/java/com/twilio/ClusterTest.java
> chore: add version

- UPGRADE.md
> chore: update upgrade doc

- CHANGES.md
Removing the jWT changelog for now to fix the changelog auto-generation
> chore: removing jwt changelog

- CHANGES.md
> chore: add changelog for jwt

- src/main/java/com/twilio/http/bearertoken/ApiTokenManager.java
- src/main/java/com/twilio/http/bearertoken/OrgsTokenManager.java
> chore: use iam token endpoint

- pom.xml
Update Gson dependency version
> chore: update dependency version

- src/main/java/com/twilio/type/App.java
- src/test/java/com/twilio/type/AppTest.java
added app endpoint type and its test case.
> chore: Add endpoint app type 2

- examples/PublicOAuthExample.md
> docs: add import to oauth example
