src/main/java/com/twilio/sdk/verbs/Verb.java
Currently ```.toEscapedXML()``` or ```.toXML(true)``` only escapes the root body and not its children. This PR will also escape the verb's children.
=> Make sure children are escaped properly in TwiML XML

pom.xml, src/main/java/com/twilio/sdk/CapabilityToken.java, src/main/java/com/twilio/sdk/client/TwilioCapability.java, src/main/java/com/twilio/sdk/verbs/Verb.java
This PR uses a more up to date version of commons-lang (3.x), there are no deep changes but it would allow to avoid having commons-lang 2.x coming through maven transitive dependencies.
=> upgrade to commons-lang3

src/main/java/com/twilio/sdk/resource/InstanceResource.java
SimpleDateFormat is not thread safe, and so accesses to it should be protected or it should be made not static.
=> fix thread safety issue

src/main/java/com/twilio/sdk/verbs/Dial.java
See the [TwiML documentation](https://www.twilio.com/docs/api/twiml/dial) which describes the recording feature
=> Added support for 'record' verb attribute to enable / disable recording both legs both legs of a call within the associated <Dial> verb

src/main/java/com/twilio/sdk/resource/instance/Call.java, src/main/java/com/twilio/sdk/resource/list/NotificationList.java, src/test/java/com/twilio/sdk/resource/list/NotificationListTest.java
This has been in the API for some time but wasn't possible through this library.
Usage:
```
NotificationList notifications = call.getNotifications();
```
=> add access to notifications subresource from a call

src/main/java/com/twilio/sdk/verbs/Client.java, src/main/java/com/twilio/sdk/verbs/Number.java, src/test/java/com/twilio/sdk/verbs/ClientTest.java, src/test/java/com/twilio/sdk/verbs/NumberTest.java
Fixes incorrect name of the generated attribute - statusCallbackEvents - to a singular form. This is a continuation of #210 and it partially fixes DEVX-1997.
=> Fix of the 'statusCallbackEvents' for Client and Number verbs

pom.xml, src/main/java/com/twilio/sdk/parser/JsonResponseParser.java, src/main/java/com/twilio/sdk/taskrouter/WorkflowConfiguration.java, src/main/java/com/twilio/sdk/taskrouter/WorkflowRule.java, src/main/java/com/twilio/sdk/taskrouter/WorkflowRuleTarget.java
Tried to keep this as small of change as possible.
This updates to 2.5.4 which is the current version of the 2.5.x which is what Amazon AWS is shipping.
This closes or supersedes #128 #130 #140 and #149
=> Upgrade to jackson 2.5.4

src/main/java/com/twilio/sdk/auth/IpMessagingGrant.java, src/test/java/com/twilio/sdk/AccessTokenTest.java, src/test/java/com/twilio/sdk/TwilioUtilsTest.java
The current grant format for IP Messaging is incorrect - this should fix that error, and also makes one of the currently failing tests for secure string comparison slightly more forgiving. It was failing regularly on my Mac.
=> fix access token for IP messaging and failing SCMP test

src/main/java/com/twilio/sdk/taskrouter/TaskRouterCapability.java, src/main/java/com/twilio/sdk/taskrouter/TaskRouterWorkerCapability.java, src/test/java/com/twilio/sdk/taskrouter/TaskRouterCapabilityTest.java
- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker
=> Loading Reservations under a Worker by default in TaskRouter JS SDK

src/main/java/com/twilio/sdk/resource/instance/taskrouter/TaskQueueStatistics.java, src/main/java/com/twilio/sdk/resource/instance/taskrouter/WorkflowStatistics.java, src/main/java/com/twilio/sdk/resource/instance/taskrouter/WorkspaceStatistics.java, src/test/java/com/twilio/sdk/resource/instance/taskrouter/TaskQueueStatisticsTest.java, src/test/java/com/twilio/sdk/resource/instance/taskrouter/WorkflowStatisticsTest.java, src/test/java/com/twilio/sdk/resource/instance/taskrouter/WorkspaceStatisticsTest.java, src/test/resources/com/twilio/sdk/resource/instance/taskrouter/task_queue_statistics.json, src/test/resources/com/twilio/sdk/resource/instance/taskrouter/workflow_statistics.json, src/test/resources/com/twilio/sdk/resource/instance/taskrouter/workspace_statistics.json, src/test/resources/com/twilio/sdk/resource/list/taskrouter/task_queues_statistics.json
GET request to TaskQueue, Workflow and Workspace Statistics will have a field "tasks_by_priority" under RealTime Stats, similar to the "tasks_by_status" field. 
Example: 
"tasks_by_priority": {"5":1}
=> Adding tasks_by_priority to task queue statistics

src/main/java/com/twilio/exception/ApiException.java, src/test/java/com/twilio/exception/ApiExceptionTest.java
The `ApiException` class allows you to pass `null` for `status` and `code` parameters.  These are stored inside the class as `java.lang.Integer`, which is fine since that is nullable.
But when you ask the exception for its code or status, those getters return primitive `int`, which throws a `NullPointerException` if the underlying value is null.  For example, this throws a NPE:
```java
ApiException e = new ApiException(“danger”);
e.getCode();
```
There are three constructors, and two of them explicitly pass `null` for these fields, which means you can safely construct an `ApiException` that will bomb later when someone innocently asks for its status or code.
This PR changes the result types on `getCode()` and `getStatusCode()` from primitive `int` to `java.lang.Integer`.
There is another …
=> Fix NPE vulnerability in ApiException getCode/getStatusCode

src/main/java/com/twilio/converter/DateConverter.java, src/test/java/com/twilio/converter/DateConverterTest.java
Fix for https://github.com/twilio/twilio-java/issues/303
=> Fix exception parsing rfc2822 dates for some locales, always use US locale

src/main/java/com/twilio/twiml/Conference.java, src/main/java/com/twilio/twiml/Dial.java, src/main/java/com/twilio/twiml/Pause.java, src/test/java/com/twilio/twiml/ConferenceTest.java, src/test/java/com/twilio/twiml/DialTest.java, src/test/java/com/twilio/twiml/PauseTest.java
According to the wiki only `Conference, Dial, and Pause` have undocumented options. However, for consistency should we add this option to all TwiML verbs - in my opinion no.
=> Ability to add undocumented options to requests

src/test/java/com/twilio/http/RequestTest.java
Hi,
I propose this changes to [specify](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/http/Request.java#L259) the `equals()` method of `com.twilio.http.Request`, against object and null value
=> add test equals() on request

src/main/java/com/twilio/type/PhoneNumberPrice.java, src/test/java/com/twilio/type/PhoneNumberPriceTest.java
The Twilio REST API returns the key "number_type" instead of "type".
https://www.twilio.com/docs/api/pricing/phonenumbers#phone-number-price
This pull request solves the issue [DEVED-2155](https://issues.corp.twilio.com/browse/DEVED-2155).
=> Fix PhoneNumberPrice deserialization

pom.xml, src/main/java/com/twilio/jwt/taskrouter/Policy.java, src/main/java/com/twilio/taskrouter/TaskRouting.java, src/main/java/com/twilio/taskrouter/Workflow.java, src/main/java/com/twilio/taskrouter/WorkflowRule.java, src/main/java/com/twilio/taskrouter/WorkflowRuleTarget.java, src/test/java/com/twilio/converter/CurrencyDeserializerTest.java
Related to [DEVED-2178](https://issues.corp.twilio.com/browse/DEVED-2178). It should remove some pain points when using twilio-java along other libraries with newer versions of the Jackson library.
=> Bump up Jackson dependencies to version 2.8.7

CHANGES.md, src/main/java/com/twilio/http/NetworkHttpClient.java
Example: Not using system properties as defaults:
```java
HttpClientBuilder clientBuilder = HttpClientBuilder.create();
NetworkHttpClient twilioClient = new NetworkHttpClient(clientBuilder);
```
=> Allow passing custom HttpClientBuilder to NetworkHttpClient

src/main/java/com/twilio/http/NetworkHttpClient.java
Hello, and great work on this library!
We've recently discovered an HTTP connection leak can occur under network edge conditions. 
This is a pull request that ensures that "... that the entity content has been fully consumed **and** the underlying stream has been closed" (https://hc.apache.org/httpcomponents-client-4.5.x/tutorial/html/fundamentals.html)
Specifically, the code below reads the full response (while still preserving the code's dependency on accessing the response InputStream), as well as guaranteeing that the response is closed. Both of these steps are important, and are consistent with the HttpClient recommendations.
Let me know if you have any questions! We've been running these modifications in Production for several days now and have not seen the connection leak since.
=> Ensuring all HTTP connections are properly closed

src/main/java/com/twilio/jwt/validation/RequestCanonicalizer.java, src/test/java/com/twilio/jwt/validation/RequestCanonicalizerTest.java, src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
Generalizes the LOWERCASE_KEYS function into NORMALIZE_HEADERS.  Additionally strips default ports on the Host header for signature generation (PKCV).
=> Strip default ports in RequestCanonicalizer

src/main/java/com/twilio/twiml/GenericNode.java, src/main/java/com/twilio/twiml/TwiML.java, src/test/java/com/twilio/twiml/FaxResponseTest.java, src/test/java/com/twilio/twiml/MessagingResponseTest.java, src/test/java/com/twilio/twiml/VoiceResponseTest.java
- Allow specifying name for a TwiML node
- Add tests for `MessagingResponse`, `VoiceResponse` and `FaxResponse`
Note: tests are auto-generated; will make a separate PR for the code generation.
=> Allow adding TwiML children with generic tag names

src/main/java/com/twilio/security/RequestValidator.java, src/test/java/com/twilio/security/RequestValidatorTest.java
If we want to validate requests that have a POST body payload, this allows us to compare it against the `bodySHA256` parameter that will be sent from the Twilio Webhook.
=> Add a method for validation of JSON body

src/main/java/com/twilio/http/Response.java, src/test/java/com/twilio/http/ResponseTest.java
Since some stream implementations return 0 for `available()` even though there is more data (since it's non-blocking), this instead uses Scanner's `hasNext` method to check if there is additional data that we could expect (which is blocking, as expected).
=> Update Response to use Scanner hasNext()

src/main/java/com/twilio/http/ValidationInterceptor.java, src/main/java/com/twilio/jwt/validation/ValidationToken.java, src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
Previously, this library was doing direct modification of the headers object passed to `ValidationToken.fromHttpRequest`.
This change instead clones that object so we can do with it what we desire.
Additionally, this adds a test for thread safety of the `ValidationInterceptor#process` method call. This test correctly failed before the modifications to `ValidationInterceptor.java` were made.
=> Clone the headers object and add test for thread safety

pom.xml
jackson: `2.8.11` -> latest `2.9.7`
Upgrade due to security vulnerability in older version
httpclient: `4.5.2` -> `4.5.6`
httpcore: `4.4.4` -> `4.4.10`
Fix connection issues per upgrades to Apache HttpComponents (https://github.com/twilio/twilio-java/issues/443)
=> Bump httpclient httpcore and jackson version

pom.xml
- Bump `jackson` library version to 2.9.8 due to vulnerabilities in `jackson-databind` versions >= 2.9.0 and < 2.9.8
=> Upgrade jackson library to 2.9.8

src/main/java/com/twilio/security/RequestValidator.java, src/test/java/com/twilio/security/RequestValidatorTest.java
Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.
=> Switch body validator to use hex instead of base64

src/main/java/com/twilio/jwt/validation/ValidationToken.java, src/test/java/com/twilio/jwt/validation/ValidationTokenTest.java
This change no longer assumes that `POST` requests will be enclosing an `entity`. If the request actually does enclose an `entity`, then *use it*. Otherwise, don't try to.
=> Allow POST requests that are void of a body or any params when using the ValidationClient

.travis.yml
=> Add more JDK versions to Travis CI config

src/main/java/com/twilio/security/RequestValidator.java
The parse method being called was deprecated, so I removed it and changed the call to the same call used in the library. I also removed an unnecessary type declaration in a generic, and an unused import. 
=> Code cleanup

pom.xml, src/test/java/com/twilio/compliance/ComplianceTest.java
- enforce consistency across all Resource subclasses
- block [java.util.logging] usage
=> Add [archunit] rules

pom.xml, src/main/java/com/twilio/example/ValidationExample.java, src/main/java/com/twilio/http/Request.java, src/main/java/com/twilio/security/RequestValidator.java
Hi,
At work, we use your twilio library to send sms messages.  We use Sonatype vulnerability scanner to scan our code base for security vulnerabilities.  Apache commons codec was picked up with issues for Base64, BCodec, Base32 classes.  There's no CVE (Common Vulnerabilities and Exposures), but Sonatype raised an internal issue referencing apache issue below.
https://issues.apache.org/jira/browse/CODEC-134
The fix was to use java util Base64 encoder and remove apache commons codec dependency.  Maven tests passed.
I also added Spotbugs scan to the compile phase to highlight potential issues, which doesn't fail the build on error.  You can kick it off independently using 'mvn spotbugs:check'.
> All third-party contributors acknowledge that any contributions they …
=> Replace commons codec

owasp-dependency-checker-suppressions.xml, pom.xml
Issues found and libraries updated to latest versions:
guava-18.0: CVE-2018-10237
jackson-databind-2.9.8: CVE-2019-12086
Fixes issue #451 
- [X ] I acknowledge that all my contributions will be made under the project's license.
=> Update library dependencies

src/main/java/com/twilio/type/SubscribeRule.java, src/test/java/com/twilio/type/SubscribeRuleTest.java
Before GA of the Bandwidth Profile API, we have decided to change the TrackPriority to `STANDARD` as this more accurately describes the priority we're using.
=> VIDEO-2338 TrackPriority.STANDARD before GA

src/main/java/com/twilio/converter/Promoter.java, src/main/java/com/twilio/type/Twiml.java, src/test/java/com/twilio/converter/PromoterTest.java
Adding new type to use for API Definitions specificity.
=> fix: add new Twiml type to deal with constructor overloading issue

src/main/java/com/twilio/taskrouter/WorkflowRuleTarget.java, src/test/java/com/twilio/taskrouter/WorkflowRuleTargetTest.java
Edited WorkflowRuleTarget class to add missing order_by and skip_if parameters
=> feat: add 'order_by' and 'skip_if' parameters in WorkflowRuleTarget

pom.xml, src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java, src/test/java/com/twilio/jwt/client/ClientCapabilityTest.java, src/test/java/com/twilio/jwt/taskrouter/TaskRouterCapabilityTest.java
This updates the jjwt dependency to 0.10.7.
=> chore: Update jjwt dependency version 0.10.7

src/main/java/com/twilio/jwt/accesstoken/ChatGrant.java, src/main/java/com/twilio/jwt/accesstoken/ConversationsGrant.java, src/main/java/com/twilio/jwt/accesstoken/IpMessagingGrant.java, src/main/java/com/twilio/jwt/accesstoken/SyncGrant.java, src/main/java/com/twilio/jwt/accesstoken/TaskRouterGrant.java, src/main/java/com/twilio/jwt/accesstoken/VideoGrant.java, src/main/java/com/twilio/jwt/accesstoken/VoiceGrant.java, src/test/java/com/twilio/jwt/accesstoken/AccessTokenTest.java
The JWT payloads should not contain null values. This fix ensures any null values do not get included when serializing the `Payload` class.
Reference: https://www.baeldung.com/jackson-ignore-null-fields
=> fix: Do not include null values in JWT payloads

src/main/java/com/twilio/Twilio.java, src/test/java/com/twilio/TwilioTest.java
Fixes #431 
Initial attempt at trying to mitigate some threading issues in the Twilio API. I'm a bit new to open source, but I think this should try and help (or at least pave the initial steps) for issue #431
I didn't quite see the reason why a `boolean` was necessary (as mentioned by @bohnman in #431). Regardless if the executor service is set by the user or if it is generated internally, we should shutdown the executor service anyway, am I right?
Oh, and I think there might have been a small typo in the `setUsername` method. I updated that as well.
=> fix: shut down executorService thread automatically to allow the JVM to shut down gracefully

src/main/java/com/twilio/http/NetworkHttpClient.java
Fixes #513 
This PR adds in a new constructor to the `NetworkHttpClient` class to take in a custom request config object.
=> fix: adding new constructor

src/main/java/com/twilio/http/Request.java, src/test/java/com/twilio/http/RequestTest.java
Fixes a bug in datetime filter when the DateTime instances are constructed with a timezone different than UTC. i.e.: `DateTime.now().minusMinutes(5)`. `QUERY_STRING_DATE_TIME_FORMAT` strips the timezone information from the query parameter.
- [x ] I acknowledge that all my contributions will be made under the project's license
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [ x] I have titled the PR appropriately
- [ x] I have updated my branch with the master branch
- [ x] I have added tests that prove my fix is effective or that my feature works
=> fix: Fix datetime filter when the DateTime instances have timezone other than UTC

src/main/java/com/twilio/http/NetworkHttpClient.java, src/main/java/com/twilio/http/Response.java, src/main/java/com/twilio/http/ValidationClient.java
The default HTTP client stores 'Last Request' and 'Last Response' information for access to more data about the raw API request/response. The response object did not contain the headers until now.
=> feat: include API response headers in 'Last Response'

src/main/java/com/twilio/http/HttpClient.java, src/main/java/com/twilio/http/NetworkHttpClient.java, src/main/java/com/twilio/http/TwilioRestClient.java, src/main/java/com/twilio/http/ValidationClient.java, src/test/java/com/twilio/http/TwilioRestClientTest.java
Fetching a BulkExport for a single day returns a `307` with the AWS URL for the file. With this change, the URL will now be included in the response.
=> fix: allow API redirect responses

README.md, src/main/java/com/twilio/Twilio.java
Credential and region/edge values will now default to the corresponding env vars and does not require client initialization.
=> feat: add support for environment variables

UPGRADE.md, src/main/java/com/twilio/type/IceServer.java, src/test/java/com/twilio/type/IceServerTest.java
> Developers MUST NOT use a generic hierarchical URI parser to parse a "stun" or "stuns" URI.
> Developers MUST NOT use a generic hierarchical URI parser to parse a "turn" or "turns" URI.
Fixes #400
=> fix!: replace ICE Server URL properties with String types

src/main/java/com/twilio/Twilio.java
Reduces multi-threading issues when initializing the static 'Twilio' by synchronizing access.
Fixes #430
=> feat: make static 'Twilio' access synchronized

src/test/java/com/twilio/compliance/ComplianceTest.java
use ArchUnit to detect JodaTime usage
=> test: use ArchUnit to detect JodaTime usage

src/test/java/com/twilio/http/RequestTest.java
Change RequestTest to use flexapi instead of ip-messaging
=> test: change RequestTest to use flexapi instead of ip-messaging

pom.xml, src/main/java/com/twilio/http/TwilioRestClient.java
Java module system gives warnings on reflective access to java.time.*
private fields, which are performed by Jackson when using
TwilioRestClient.
Jackson provides a `JavaTimeModule` which configures an ObjectMapper to
use public methods instead of reflective accesss to private fields in
classes in java.time.
This PR adds the dependency for `JavaTimeModule` and adds it to the
ObjectMapper created by `TwilioRestClient`, which removes all the
warnings that I have seen.
=> fix: drop reflective access warnings to java.time.* classes

src/main/java/com/twilio/http/TwilioRestClient.java
This PR changes the access modifier for the TwilioRestClient constructor from `private` to `protected`. Allows for extending the class (e.g. for wrapping the `super.request()` method with instrumentation).
Verified that `make test` passes but haven't added any additional tests since it's just a simple access change / would just be testing a core Java feature. Lmk if we do want a test for this and I'd be happy to write something up.
=> chore: protected TwilioRestClient constructor

.travis.yml
Deploy fails with the docker-ce-18.x.x and needs to be upgraded to 20.x
[Failed job](https://app.travis-ci.com/github/twilio/twilio-java/jobs/536287600)
https://github.com/docker-library/openjdk/issues/465
https://github.com/carlossg/docker-maven/issues/221
=> fix: deploy issues

pom.xml, src/main/java/com/twilio/twiml/TwiML.java
This PR adds an ObjectMapper accessible to all TwiML Builder subclasses. It also annotates the builder's `addText` method. Both of these changes are necessary for the upcoming XML deserialization support for TwiML (see internal PR).
=> chore: setup for XML deserialization

.github/workflows/test-and-deploy.yml, pom.xml
Adds SonarCloud integration
Analysis on fork branch can be found at this [link](https://sonarcloud.io/summary/new_code?branch=add-sonarcloud-integration&id=BrimmingDev_twilio-java).
**Note: This PR will change the name of the project in SonarCloud from twilio to twilio-java once merged into main.
=> chore: added sonarcloud integration

src/main/java/com/twilio/http/HttpClient.java, src/main/java/com/twilio/http/NetworkHttpClient.java, src/main/java/com/twilio/http/ValidationClient.java
Sets a default socket config with timeout for all connections. Note that this must be applied to the connection manger and not the client builder. The client builder default socket config is only used when not given a connection manager.
Fixes #663
=> [DI-1920] fix: set socket config with blocking operation timeout

src/main/java/com/twilio/Twilio.java
Account SID is a nullable field, we should allow setting the accountSid to null for users managing multiple rest clients
=> fix: support setting null account sid

src/main/java/com/twilio/Twilio.java
Following https://github.com/twilio/twilio-java/pull/688, we should sets account sid to null if it's not used for current form of authentication
=> fix: reset account sid when using username and password only

pom.xml
Bump jackson version to 2.14.0 instead of only bumping the jackson-databind version from PR #720.
=> chore: bump jackson to 2.14.0

src/main/java/com/twilio/rest/chat/v1/ServiceUpdater.java, src/main/java/com/twilio/rest/chat/v2/ServiceUpdater.java, src/main/java/com/twilio/rest/chat/v2/service/channel/WebhookCreator.java, src/main/java/com/twilio/rest/chat/v2/service/channel/WebhookUpdater.java, src/main/java/com/twilio/rest/conversations/v1/AddressConfigurationCreator.java, src/main/java/com/twilio/rest/conversations/v1/AddressConfigurationUpdater.java, src/main/java/com/twilio/rest/conversations/v1/conversation/WebhookCreator.java, src/main/java/com/twilio/rest/conversations/v1/conversation/WebhookUpdater.java, src/main/java/com/twilio/rest/conversations/v1/service/configuration/NotificationUpdater.java, src/main/java/com/twilio/rest/conversations/v1/service/conversation/WebhookCreator.java, src/main/java/com/twilio/rest/conversations/v1/service/conversation/WebhookUpdater.java, src/main/java/com/twilio/rest/flexapi/v1/FlexFlowCreator.java, src/main/java/com/twilio/rest/flexapi/v1/FlexFlowUpdater.java, src/main/java/com/twilio/rest/ipmessaging/v1/ServiceUpdater.java, src/main/java/com/twilio/rest/ipmessaging/v2/ServiceUpdater.java, src/main/java/com/twilio/rest/ipmessaging/v2/service/channel/WebhookCreator.java, src/main/java/com/twilio/rest/ipmessaging/v2/service/channel/WebhookUpdater.java, src/main/java/com/twilio/rest/verify/v2/ServiceCreator.java, src/main/java/com/twilio/rest/verify/v2/ServiceUpdater.java, src/main/java/com/twilio/rest/verify/v2/service/entity/FactorUpdater.java, src/main/java/com/twilio/rest/verify/v2/service/entity/NewFactorCreator.java
Parameter name is incorrect for some params in addPostParams() for twilio-java v9.
Related PR: https://github.com/twilio/twilio-oai-generator/pull/419
=> fix: set correct Parameter name

README.md
Attempting to close [DEVED-5451](https://issues.corp.twilio.com/browse/DEVED-5451) by interpreting the slick example cooked up by Sam: https://github.com/childish-sambino/twilio-java-examples/tree/main/log4j2
=> docs: provide more detailed debug logging example

src/main/java/com/twilio/Domains.java, src/main/java/com/twilio/constant/EnumConstants.java, src/main/java/com/twilio/http/NetworkHttpClient.java, src/main/java/com/twilio/http/Request.java, src/main/java/com/twilio/http/ValidationClient.java, src/test/java/com/twilio/http/NetworkHttpClientTest.java, src/test/java/com/twilio/http/RequestTest.java, src/test/java/com/twilio/http/ValidationClientTest.java
Added domain url for messaging bulk api
=> chore: added preview messaging domain url

src/main/java/com/twilio/Twilio.java, src/test/java/com/twilio/TwilioTest.java
Update validate ssl method with new security testing method
=> fix: Update validate ssl method with new security testing method

.github/workflows/test-and-deploy.yml, src/test/java/com/twilio/ClusterTest.java
adding cluster tests for orgs api
adding cluster tests for orgs api
=> fix: adding cluster tests for orgs api

pom.xml, src/main/java/com/twilio/constant/EnumConstants.java, src/test/java/com/twilio/ClusterTest.java, src/test/java/com/twilio/http/CustomHttpClient.java
Added test case for content-type 'multipart/form-data'
=> chore: added multipart test in call api

src/main/java/com/twilio/http/ValidationClient.java, src/main/java/com/twilio/http/bearertoken/BearerTokenHttpClient.java, src/main/java/com/twilio/http/bearertoken/BearerTokenNetworkHttpClient.java, src/main/java/com/twilio/http/bearertoken/BearerTokenTwilioRestClient.java, src/main/java/com/twilio/http/noauth/NoAuthHttpClient.java, src/main/java/com/twilio/http/noauth/NoAuthNetworkHttpClient.java, src/main/java/com/twilio/http/noauth/NoAuthTwilioRestClient.java, src/test/java/com/twilio/http/CustomHttpClient.java
With OAuth support HttpClient class method argument type got changed due to which it was breaking customer environment.
Before: [twilio-java/src/main/java/com/twilio/http/HttpClient.java at de885af34a8a9e71c62b488b7119bccde5abc4de · twilio/twilio-java](https://github.com/twilio/twilio-java/blob/de885af34a8a9e71c62b488b7119bccde5abc4de/src/main/java/com/twilio/http/HttpClient.java#L134) 
After: [twilio-java/src/main/java/com/twilio/http/HttpClient.java at ab74cef9752400749fe23b9d7345d8bea27864c9 · twilio/twilio-java](https://github.com/twilio/twilio-java/blob/ab74cef9752400749fe23b9d7345d8bea27864c9/src/main/java/com/twilio/http/HttpClient.java#L134) 
Revert the interface changes.
Create separate clients for BearerToken and NoAuth Requests
If you have questions, please file a [support …
=> fix: added new httpclient for noauth and bearertoken requests

README.md, UPGRADE.md, src/main/java/com/twilio/Twilio.java
=> feat!: MVR Release Preparation

src/main/java/com/twilio/http/TwilioRestClient.java, src/main/java/com/twilio/http/bearertoken/BearerTokenTwilioRestClient.java, src/main/java/com/twilio/http/noauth/NoAuthTwilioRestClient.java, src/test/java/com/twilio/http/TwilioRestClientTest.java
Adds support for providing a custom ObjectMapper to the rest client builders. If no ObjectMapper is provided to the builder, a default one which matches the existing configuration will be used. The default ObjectMapper for each rest client type will also now be held in a static variable, so we aren't instantiating a new one every time a rest client is created.
=> feat: Support custom ObjectMappers, with singleton defaults

pom.xml
ossrh has been deprecated and moved to central repo.
Reason for migration to central:
As per [doc](https://central.sonatype.org/publish/publish-guide/), The legacy OSSRH publishing service will be sunset on June 30th, 2025
Guide followed:
https://central.sonatype.org/publish/publish-portal-maven/#automatic-publishing
=> chore: added plugin for publishing to central repo
